import { Retreat } from '@/types';

export const RETREATS: Retreat[] = [
  {
    id: 'r1',
    name: 'Pura Vida Yoga Retreat',
    shortDescription: 'Sunrise yoga with Pacific Ocean views in Nosara.',
    description:
      'Nestled in the hills of Nosara, Pura Vida Yoga Retreat offers daily sunrise and sunset yoga classes with breathtaking Pacific Ocean views. Our experienced instructors guide you through vinyasa, yin, and restorative practices. Enjoy organic farm-to-table meals, holistic spa treatments, and guided nature walks through the surrounding Ostional Wildlife Refuge.',
    location: 'Nosara, Guanacaste',
    region: 'Guanacaste',
    lat: 9.9794,
    lng: -85.6504,
    price: 180,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    ],
    amenities: ['Pool', 'Spa', 'WiFi', 'Organic Meals', 'Yoga Studio', 'Nature Trails'],
    rating: 4.9,
    reviewCount: 312,
    category: 'yoga',
    duration: '3–14 nights',
    maxGuests: 20,
    available: true,
    highlights: ['Ocean view yoga decks', 'Certified instructors', 'Detox programs', 'Eco-certified'],
    contactEmail: 'info@puravidayoga.cr',
    website: 'https://puravidayoga.cr',
  },
  {
    id: 'r2',
    name: 'Arenal Jungle Wellness Lodge',
    shortDescription: 'Heal body and mind in the shadow of the Arenal Volcano.',
    description:
      'Set against the dramatic backdrop of Arenal Volcano, this award-winning wellness lodge combines volcanic hot springs, forest bathing, and integrative healing modalities. Guests enjoy unlimited access to thermal pools fed by the volcano, daily meditation sessions, and expert-led workshops on mindfulness and nutrition.',
    location: 'La Fortuna, Alajuela',
    region: 'Alajuela',
    lat: 10.4777,
    lng: -84.6438,
    price: 220,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
    ],
    amenities: ['Hot Springs', 'Forest Trails', 'Meditation Hall', 'WiFi', 'Restaurant', 'Spa'],
    rating: 4.8,
    reviewCount: 245,
    category: 'wellness',
    duration: '4–10 nights',
    maxGuests: 30,
    available: true,
    highlights: ['Volcano hot springs', 'Forest therapy', 'Waterfall tours', 'All-inclusive available'],
    contactEmail: 'info@arenalwellness.cr',
  },
  {
    id: 'r3',
    name: 'Montezuma Sacred Earth Retreat',
    shortDescription: 'Transformative plant-medicine ceremonies on the Nicoya Peninsula.',
    description:
      'On the lush Nicoya Peninsula — one of the world\'s five Blue Zones — Sacred Earth Retreat offers authentic shamanic ceremonies, cacao circles, breathwork, and sound healing. Our permaculture farm feeds guests with the freshest tropical produce. The nearby Montezuma Waterfall and pristine beaches complete the healing journey.',
    location: 'Montezuma, Puntarenas',
    region: 'Puntarenas',
    lat: 9.6560,
    lng: -85.0694,
    price: 150,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800',
      'https://images.unsplash.com/photo-1596178060810-72f53ce9a65c?w=800',
    ],
    amenities: ['Permaculture Garden', 'Ceremony Space', 'Beach Access', 'WiFi', 'Plant-based Meals'],
    rating: 4.7,
    reviewCount: 178,
    category: 'meditation',
    duration: '5–21 nights',
    maxGuests: 15,
    available: true,
    highlights: ['Blue Zone location', 'Waterfall access', 'Cacao ceremony', 'Plant-based cuisine'],
    contactEmail: 'info@sacredearthcr.com',
  },
  {
    id: 'r4',
    name: 'Tamarindo Surf & Soul Retreat',
    shortDescription: 'Catch waves and find your flow at Costa Rica\'s surf capital.',
    description:
      'Experience the perfect fusion of surf coaching, yoga, and tropical living in the legendary beach town of Tamarindo. From complete beginners to intermediate surfers, our ISA-certified instructors design personalized surf programs. Morning yoga, afternoon surf sessions, and sunset beach bonfires make every day unforgettable.',
    location: 'Tamarindo, Guanacaste',
    region: 'Guanacaste',
    lat: 10.2992,
    lng: -85.8408,
    price: 195,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800',
      'https://images.unsplash.com/photo-1455729552865-3658a5d39692?w=800',
    ],
    amenities: ['Surfboard Rental', 'Yoga Deck', 'Pool', 'Beach Access', 'WiFi', 'Bar'],
    rating: 4.8,
    reviewCount: 421,
    category: 'surf',
    duration: '3–14 nights',
    maxGuests: 25,
    available: true,
    highlights: ['ISA-certified instructors', 'Beginner to advanced', 'Daily yoga', 'Sunset ceremonies'],
    contactEmail: 'info@tamarindosurf.cr',
  },
  {
    id: 'r5',
    name: 'Manuel Antonio Eco Sanctuary',
    shortDescription: 'Luxury eco-lodge steps from Manuel Antonio National Park.',
    description:
      'Wake up to monkeys swinging through the treetops at this boutique eco-sanctuary adjoining Manuel Antonio National Park. Certified by CST (Certificate for Sustainable Tourism), we operate fully on solar power with rainwater harvesting. Morning jungle walks, beach yoga, and evening wellness rituals restore your senses in paradise.',
    location: 'Manuel Antonio, Puntarenas',
    region: 'Puntarenas',
    lat: 9.3898,
    lng: -84.1371,
    price: 260,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
      'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800',
    ],
    amenities: ['Infinity Pool', 'Wildlife Tours', 'Spa', 'Organic Restaurant', 'WiFi', 'Beach Access'],
    rating: 4.9,
    reviewCount: 389,
    category: 'eco',
    duration: '3–14 nights',
    maxGuests: 18,
    available: true,
    highlights: ['CST certified', 'Solar powered', 'Wildlife watching', 'National park access'],
    contactEmail: 'info@maecosanctuary.cr',
  },
  {
    id: 'r6',
    name: 'Dominical Adventure Retreat',
    shortDescription: 'Surf, hike, kayak and zip-line in the South Pacific.',
    description:
      'For the adventurous soul, Dominical Adventure Retreat combines world-class surfing with rainforest trekking, kayaking in mangroves, and soaring zip-lines. Nestled between mountains and the wild Pacific coast, this all-inclusive retreat packages adrenaline-fueled activities with restorative yoga and hearty local cuisine.',
    location: 'Dominical, Puntarenas',
    region: 'Puntarenas',
    lat: 9.2424,
    lng: -83.8594,
    price: 175,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800',
    ],
    amenities: ['Surf Lessons', 'Zip-line', 'Kayak Tours', 'Yoga', 'WiFi', 'Bar & Restaurant'],
    rating: 4.6,
    reviewCount: 203,
    category: 'adventure',
    duration: '4–14 nights',
    maxGuests: 22,
    available: true,
    highlights: ['Adventure packages', 'Surf coaching', 'Mangrove kayak', 'All-inclusive option'],
    contactEmail: 'info@dominicaladventure.cr',
  },
  {
    id: 'r7',
    name: 'Corcovado Rainforest Retreat',
    shortDescription: 'Immerse yourself in the most biodiverse place on Earth.',
    description:
      'On the edge of Corcovado National Park — dubbed "the most biologically intense place on Earth" by National Geographic — this remote retreat offers guided wildlife tours with scarlet macaws, tapirs, and jaguars. Accommodation is in open-air jungle bungalows powered entirely by solar energy. Completely off-the-grid and utterly transformative.',
    location: 'Drake Bay, Osa Peninsula',
    region: 'Osa Peninsula',
    lat: 8.6880,
    lng: -83.6410,
    price: 230,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800',
      'https://images.unsplash.com/photo-1511497584788-876760111969?w=800',
    ],
    amenities: ['Wildlife Tours', 'Jungle Bungalows', 'Solar Power', 'Rainforest Trails', 'Meals Included'],
    rating: 4.9,
    reviewCount: 134,
    category: 'jungle',
    duration: '3–10 nights',
    maxGuests: 12,
    available: true,
    highlights: ['Corcovado access', 'Wildlife guides', 'Zero carbon footprint', 'Scarlet macaws'],
    contactEmail: 'info@corcovadoretreat.cr',
  },
  {
    id: 'r8',
    name: 'Santa Teresa Beach Bliss',
    shortDescription: 'World-class surf and yoga on one of Costa Rica\'s best beaches.',
    description:
      'Santa Teresa consistently ranks among the world\'s top surf destinations and this boutique retreat puts you right in the heart of it. Blending surf culture with holistic wellness, guests enjoy daily yoga, world-class waves steps from their bungalow, artisanal coffee each morning, and vibrant local culture in the evenings.',
    location: 'Santa Teresa, Puntarenas',
    region: 'Puntarenas',
    lat: 9.6395,
    lng: -85.1729,
    price: 160,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
      'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800',
    ],
    amenities: ['Beach Access', 'Surf Rental', 'Yoga Classes', 'Café', 'WiFi', 'Hammocks'],
    rating: 4.7,
    reviewCount: 267,
    category: 'beach',
    duration: '3–21 nights',
    maxGuests: 16,
    available: true,
    highlights: ['Top surf beach', 'Sunset yoga', 'Artisanal coffee', 'Vibrant nightlife'],
    contactEmail: 'info@santateresabliss.cr',
  },
  {
    id: 'r9',
    name: 'Sarapiquí Jungle Detox',
    shortDescription: 'Deep jungle detox retreat in the Caribbean lowlands.',
    description:
      'Surrounded by primary rainforest in the Sarapiquí lowlands near the Caribbean coast, this retreat specialises in detox programmes combining juice fasting, herbal medicine, and daily yoga. Expert nutritionists and naturopathic doctors guide each guest through a personalised detox journey. White-water rafting and wildlife canoe tours complete the experience.',
    location: 'Sarapiquí, Heredia',
    region: 'Heredia',
    lat: 10.4749,
    lng: -84.0132,
    price: 140,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=800',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    ],
    amenities: ['Juice Bar', 'Medical Staff', 'Yoga', 'River Tours', 'WiFi', 'Herbal Garden'],
    rating: 4.6,
    reviewCount: 156,
    category: 'wellness',
    duration: '7–21 nights',
    maxGuests: 14,
    available: true,
    highlights: ['Medical detox team', 'Juice fasting', 'River rafting', 'Caribbean birdwatching'],
    contactEmail: 'info@sarapiquidetox.cr',
  },
  {
    id: 'r10',
    name: 'Monteverde Cloud Forest Zen',
    shortDescription: 'Mindfulness and meditation surrounded by mystic cloud forest.',
    description:
      'High in the Monteverde Cloud Forest Reserve, this serene Zen retreat offers an unmatched setting for deep meditation and mindfulness practice. Surrounded by mist-covered trees and the songs of resplendent quetzals, guests follow structured silent retreats, Vipassana meditation, and mindful hiking on the famous hanging bridges.',
    location: 'Monteverde, Puntarenas',
    region: 'Puntarenas',
    lat: 10.3022,
    lng: -84.7985,
    price: 170,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=800',
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    ],
    amenities: ['Meditation Halls', 'Silent Zones', 'Cloud Forest Trails', 'Vegetarian Meals', 'Library'],
    rating: 4.8,
    reviewCount: 198,
    category: 'meditation',
    duration: '5–14 nights',
    maxGuests: 18,
    available: true,
    highlights: ['Cloud forest setting', 'Quetzal sightings', 'Hanging bridges', 'Vipassana programs'],
    contactEmail: 'info@monteverdezen.cr',
  },
  {
    id: 'r11',
    name: 'Papagayo Luxury Wellness Resort',
    shortDescription: 'Five-star wellness on the turquoise Gulf of Papagayo.',
    description:
      'Where luxury meets holistic healing on the Gulf of Papagayo, Papagayo Wellness Resort offers Forbes 5-star service with world-class spa treatments, Ayurvedic programmes, private beach, and a fleet of yachts for island-hopping. Michelin-inspired cuisine, infinity pools, and personalised wellness consultations redefine the meaning of retreat.',
    location: 'Gulf of Papagayo, Guanacaste',
    region: 'Guanacaste',
    lat: 10.5903,
    lng: -85.6672,
    price: 550,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800',
    ],
    amenities: ['Private Beach', 'Infinity Pool', 'Yacht Charter', 'Ayurveda Spa', 'Fine Dining', 'Butler Service'],
    rating: 5.0,
    reviewCount: 89,
    category: 'wellness',
    duration: '3–30 nights',
    maxGuests: 40,
    available: true,
    highlights: ['5-star luxury', 'Private beach', 'Yacht tours', 'Ayurvedic medicine'],
    contactEmail: 'reservations@papagayowellness.cr',
  },
  {
    id: 'r12',
    name: 'Tortuguero Turtle & Yoga Lodge',
    shortDescription: 'Witness sea turtle nesting alongside transformative yoga.',
    description:
      'Accessible only by boat or small plane, Tortuguero\'s remote Caribbean canals hide this magical yoga lodge. From July to October, witness thousands of giant leatherback and green sea turtles nesting on the protected beach. Canoe through jungle canals spotting caimans, manatees, and exotic birds between yoga and meditation sessions.',
    location: 'Tortuguero, Limón',
    region: 'Limón',
    lat: 10.5422,
    lng: -83.5025,
    price: 190,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1559521783-1d1599583485?w=800',
      'https://images.unsplash.com/photo-1518272267798-e4c6c3b4f9f6?w=800',
    ],
    amenities: ['Canal Tours', 'Turtle Tours', 'Yoga', 'Meals Included', 'Kayaking', 'WiFi'],
    rating: 4.8,
    reviewCount: 167,
    category: 'eco',
    duration: '3–10 nights',
    maxGuests: 16,
    available: true,
    highlights: ['Sea turtle nesting', 'Canal kayaking', 'Caiman spotting', 'Remote paradise'],
    contactEmail: 'info@tortuguero-yoga.cr',
  },
];
