import { Tour } from '@/types';

export const TOURS: Tour[] = [
  {
    id: 't1',
    name: 'Mountain Bike Rental – Full Day',
    description: 'Explore jungle trails and coastal roads on a quality mountain bike. Helmet and lock included. Map and route suggestions provided.',
    category: 'bike_rental',
    price: 25,
    priceUnit: 'per day',
    duration: '1 day',
    location: 'Nationwide',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    available: true,
    maxParticipants: 20,
  },
  {
    id: 't2',
    name: 'Private Airport Shuttle',
    description: 'Comfortable, air-conditioned private shuttle from SJO or LIR airport to any destination in Costa Rica. 24/7 service.',
    category: 'shuttle',
    price: 65,
    priceUnit: 'per person',
    duration: 'Varies',
    location: 'San José / Liberia Airport',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600',
    available: true,
    maxParticipants: 8,
  },
  {
    id: 't3',
    name: 'Shared Shuttle – Inter-City',
    description: 'Affordable shared shuttle service connecting all major tourist destinations: San José, Tamarindo, Nosara, La Fortuna, Manuel Antonio, and more.',
    category: 'shuttle',
    price: 25,
    priceUnit: 'per person',
    duration: 'Varies',
    location: 'Nationwide',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600',
    available: true,
    maxParticipants: 12,
  },
  {
    id: 't4',
    name: 'Private Taxi – Local Transfer',
    description: 'Licensed, metered taxis for local transfers. Book in advance for stress-free transfers to beaches, restaurants, and attractions.',
    category: 'taxi',
    price: 20,
    priceUnit: 'per trip',
    duration: 'Varies',
    location: 'Nationwide',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600',
    available: true,
    maxParticipants: 4,
  },
  {
    id: 't5',
    name: 'Table Reservation – La Soda Típica',
    description: 'Authentic Costa Rican casado lunches and dinners at a beloved local soda. Reserve your table in advance and enjoy gallo pinto, fresh ceviche, and tropical juices.',
    category: 'restaurant',
    price: 0,
    priceUnit: 'free reservation',
    duration: 'Dinner or Lunch',
    location: 'San José',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600',
    available: true,
    maxParticipants: 10,
  },
  {
    id: 't6',
    name: 'Boutique Hotel – Casa Tropical',
    description: 'Charming tropical boutique hotel in the heart of Tamarindo. Private rooms with ocean views, pool, and complimentary breakfast.',
    category: 'hotel',
    price: 110,
    priceUnit: 'per night',
    duration: 'Flexible',
    location: 'Tamarindo, Guanacaste',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600',
    available: true,
    maxParticipants: 2,
  },
  {
    id: 't7',
    name: 'AirBnB-style Casa Amanecer',
    description: 'Fully equipped beachfront house for 2–8 guests. Full kitchen, ocean views, hammocks, BBQ, and private garden. Walk to surf breaks and restaurants.',
    category: 'airbnb',
    price: 180,
    priceUnit: 'per night',
    duration: 'Flexible',
    location: 'Manuel Antonio',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600',
    available: true,
    maxParticipants: 8,
  },
  {
    id: 't8',
    name: 'Arenal Volcano & Hot Springs Tour',
    description: 'Full-day guided tour to Arenal Volcano National Park followed by a relaxing evening in natural volcanic hot springs. Transport and lunch included.',
    category: 'tour',
    price: 95,
    priceUnit: 'per person',
    duration: '10 hours',
    location: 'La Fortuna',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
    available: true,
    maxParticipants: 14,
  },
  {
    id: 't9',
    name: 'Surf Lesson – Beginner (2 hrs)',
    description: 'ISA-certified instructor, surfboard and rash guard included. Best beaches selected daily based on conditions. Groups max 4 students per instructor.',
    category: 'surf',
    price: 65,
    priceUnit: 'per person',
    duration: '2 hours',
    location: 'Tamarindo / Jaco / Dominical',
    image: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600',
    available: true,
    maxParticipants: 4,
  },
  {
    id: 't10',
    name: 'Mangrove Kayak Tour',
    description: 'Guided 3-hour kayak through mangrove tunnels spotting crocodiles, monkeys, and exotic birds. Equipment, water, and snacks provided.',
    category: 'kayak',
    price: 55,
    priceUnit: 'per person',
    duration: '3 hours',
    location: 'Sierpe / Tárcoles',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
    available: true,
    maxParticipants: 10,
  },
  {
    id: 't11',
    name: 'Zip-line Canopy Adventure',
    description: 'Soar through the forest canopy on 10 zip-lines up to 1km long. Safety equipment and certified guides. Minimum age 8, max weight 120kg.',
    category: 'zip_line',
    price: 75,
    priceUnit: 'per person',
    duration: '3 hours',
    location: 'Monteverde / La Fortuna / Manuel Antonio',
    image: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600',
    available: true,
    maxParticipants: 15,
  },
  {
    id: 't12',
    name: 'Nauyaca Waterfalls Hike',
    description: 'Trek 5 miles through tropical forest to the stunning two-tiered Nauyaca Waterfalls. Horse-back option available. Swim in crystal-clear natural pools.',
    category: 'waterfall',
    price: 45,
    priceUnit: 'per person',
    duration: '6 hours',
    location: 'Dominical',
    image: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=600',
    available: true,
    maxParticipants: 12,
  },
  {
    id: 't13',
    name: 'Corcovado Wildlife Safari',
    description: 'Full-day guided trek inside Corcovado National Park with a naturalist guide. Spot tapirs, scarlet macaws, jaguars, and poison dart frogs.',
    category: 'wildlife',
    price: 120,
    priceUnit: 'per person',
    duration: '8 hours',
    location: 'Osa Peninsula',
    image: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600',
    available: true,
    maxParticipants: 8,
  },
  {
    id: 't14',
    name: 'Costa Rican Cooking Class',
    description: 'Learn to cook traditional Costa Rican dishes: gallo pinto, tamales, ceviche, and tres leches. Market visit included. Take home the recipes.',
    category: 'cooking',
    price: 70,
    priceUnit: 'per person',
    duration: '4 hours',
    location: 'San José / Tamarindo / Manuel Antonio',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600',
    available: true,
    maxParticipants: 8,
  },
  {
    id: 't15',
    name: 'E-Bike Rental – City & Coast',
    description: 'Electric mountain bike for effortless exploration of coastal and mountain routes. Battery range 60km, includes helmet, lock, and phone holder.',
    category: 'bike_rental',
    price: 45,
    priceUnit: 'per day',
    duration: '1 day',
    location: 'San José / Tamarindo / Manuel Antonio',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    available: true,
    maxParticipants: 10,
  },
];
