import { Retreat } from '@/types';

export const RETREATS: Retreat[] = [
  {
    id: 'r1',
    name: 'Nosara Yoga Retreat',
    description:
      'Immerse yourself in the tranquil beauty of Nosara, a world-renowned surf and yoga destination on Costa Rica\'s Nicoya Peninsula. Daily yoga classes with experienced instructors, organic farm-to-table meals, and stunning Pacific sunsets await you. Our eco-lodge is nestled in the lush jungle just minutes from the pristine beach.',
    shortDescription: 'Daily yoga, organic meals & Pacific sunsets in Nosara.',
    location: 'Nosara, Guanacaste',
    region: 'Guanacaste',
    lat: 9.9792,
    lng: -85.6539,
    price: 150,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&auto=format&fit=crop',
    ],
    amenities: ['WiFi', 'Yoga Studio', 'Spa', 'Pool', 'Organic Restaurant', 'Beach Access'],
    rating: 4.9,
    reviewCount: 127,
    category: 'yoga',
    duration: '7 days',
    maxGuests: 20,
    available: true,
    highlights: ['Morning & evening yoga', 'Beachfront meditation', 'All meals included', 'Airport transfer'],
    contactEmail: 'info@nosarayoga.com',
    website: 'https://nosarayoga.com',
  },
  {
    id: 'r2',
    name: 'La Fortuna Adventure Camp',
    description:
      'Based at the foot of the majestic Arenal Volcano, our adventure camp combines thrilling outdoor activities with mindful relaxation. Hike through cloud forests, soak in natural hot springs, white-water raft the Sarapiquí River, and zip-line through the jungle canopy. Perfect for adventurous souls seeking both excitement and peace.',
    shortDescription: 'Volcano hikes, hot springs & zip-lining at Arenal.',
    location: 'La Fortuna, Alajuela',
    region: 'Central Valley',
    lat: 10.4630,
    lng: -84.6440,
    price: 180,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1518623489648-a173ef7824f3?w=800&auto=format&fit=crop',
    ],
    amenities: ['WiFi', 'Hot Springs', 'Guided Tours', 'Restaurant', 'Zip-line', 'Kayak'],
    rating: 4.8,
    reviewCount: 214,
    category: 'adventure',
    duration: '5 days',
    maxGuests: 30,
    available: true,
    highlights: ['Arenal Volcano hike', 'Natural hot springs', 'White-water rafting', 'Night wildlife tour'],
    contactEmail: 'adventure@lafortuna.cr',
  },
  {
    id: 'r3',
    name: 'Uvita Beach Wellness Retreat',
    description:
      'Find your balance at our luxury wellness retreat on the stunning Whale\'s Tail beach in Uvita. We offer holistic healing through daily yoga, massage therapy, sound healing, and guided meditation. The retreat overlooks Marino Ballena National Park, offering opportunities to spot humpback whales and dolphins.',
    shortDescription: 'Holistic wellness with whale watching in Uvita.',
    location: 'Uvita, Puntarenas',
    region: 'South Pacific',
    lat: 9.1547,
    lng: -83.7373,
    price: 220,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&auto=format&fit=crop',
    ],
    amenities: ['WiFi', 'Spa', 'Infinity Pool', 'Yoga Deck', 'Meditation Hall', 'Whale Watching'],
    rating: 4.9,
    reviewCount: 98,
    category: 'wellness',
    duration: '10 days',
    maxGuests: 16,
    available: true,
    highlights: ['Whale watching tours', 'Sound healing sessions', 'Personalized wellness plan', 'Organic vegan cuisine'],
    contactEmail: 'wellness@uvitabeach.com',
  },
  {
    id: 'r4',
    name: 'Osa Peninsula Jungle Lodge',
    description:
      'Deep in the Osa Peninsula, home to the most biodiverse place on Earth, our jungle lodge offers an unparalleled eco-adventure. Wake up to howler monkeys, spot rare birds and poison dart frogs, and explore Corcovado National Park with expert naturalist guides. An authentic rainforest experience.',
    shortDescription: 'Eco-adventure in the world\'s most biodiverse rainforest.',
    location: 'Puerto Jiménez, Puntarenas',
    region: 'Osa Peninsula',
    lat: 8.5328,
    lng: -83.3000,
    price: 195,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop',
    ],
    amenities: ['Naturalist Guides', 'Corcovado Access', 'Kayak', 'Organic Meals', 'Solar Power'],
    rating: 4.7,
    reviewCount: 63,
    category: 'jungle',
    duration: '7 days',
    maxGuests: 12,
    available: true,
    highlights: ['Corcovado National Park guided tour', 'Scarlet macaw spotting', 'Night jungle walk', 'Dolphin snorkeling'],
    contactEmail: 'info@osalodge.cr',
  },
  {
    id: 'r5',
    name: 'Santa Teresa Surf & Soul',
    description:
      'Santa Teresa is one of Costa Rica\'s most vibrant beach communities, and our surf retreat captures its free-spirited energy. Morning surf lessons for all levels, afternoon yoga on the beach, and evening bonfires under the stars. Our boutique bungalows are steps from the world-famous breaks.',
    shortDescription: 'Surf lessons, beach yoga & bonfires in Santa Teresa.',
    location: 'Santa Teresa, Puntarenas',
    region: 'Nicoya Peninsula',
    lat: 9.6369,
    lng: -85.1699,
    price: 160,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&auto=format&fit=crop',
    ],
    amenities: ['Surfboard Rental', 'Yoga Studio', 'Beach Bar', 'WiFi', 'Surf Lessons'],
    rating: 4.8,
    reviewCount: 156,
    category: 'surf',
    duration: '7 days',
    maxGuests: 24,
    available: true,
    highlights: ['Daily surf lessons', 'Yoga on the beach', 'Sunset bonfires', 'Surf photo package'],
    contactEmail: 'ride@santateresasurf.com',
  },
  {
    id: 'r6',
    name: 'Monteverde Cloud Forest Retreat',
    description:
      'High in the misty Monteverde Cloud Forest, our retreat offers a magical escape into one of the world\'s rarest ecosystems. Guided canopy walks, birdwatching with over 400 species including the resplendent quetzal, and meditation in the cloud-kissed forest. An ethereal experience for nature lovers.',
    shortDescription: 'Birdwatching & meditation in the mystical cloud forest.',
    location: 'Monteverde, Puntarenas',
    region: 'Central Valley',
    lat: 10.3025,
    lng: -84.8178,
    price: 175,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&auto=format&fit=crop',
    ],
    amenities: ['Guided Tours', 'Birdwatching', 'Canopy Walk', 'Organic Restaurant', 'Meditation Space'],
    rating: 4.9,
    reviewCount: 89,
    category: 'meditation',
    duration: '5 days',
    maxGuests: 14,
    available: true,
    highlights: ['Resplendent quetzal spotting', 'Night hike', 'Cheese factory visit', 'Sky tram ride'],
    contactEmail: 'cloud@monteverde-retreat.com',
  },
  {
    id: 'r7',
    name: 'Manuel Antonio Eco Lodge',
    description:
      'Perched above Manuel Antonio National Park, arguably the most beautiful park in Costa Rica, our eco lodge offers panoramic ocean views from every bungalow. Spot sloths, monkeys, and rare birds, swim in deserted coves, and recharge with daily yoga sessions overlooking the Pacific.',
    shortDescription: 'Wildlife encounters & ocean views at Manuel Antonio.',
    location: 'Manuel Antonio, Puntarenas',
    region: 'Central Pacific',
    lat: 9.4108,
    lng: -84.1374,
    price: 200,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540541338537-71cf2dba8e79?w=800&auto=format&fit=crop',
    ],
    amenities: ['WiFi', 'Infinity Pool', 'Wildlife Tours', 'Yoga Deck', 'Restaurant', 'Snorkeling'],
    rating: 4.8,
    reviewCount: 182,
    category: 'eco',
    duration: '5 days',
    maxGuests: 18,
    available: true,
    highlights: ['Sloth & monkey watching', 'Private beach access', 'Snorkeling in the park', 'Sunset yoga'],
    contactEmail: 'eco@manuelantonio.cr',
  },
  {
    id: 'r8',
    name: 'Tamarindo Sunset Wellness',
    description:
      'Tamarindo is synonymous with laid-back luxury, and our wellness retreat embodies this spirit perfectly. Sunrise beach yoga, guided meditation, surf lessons, sport fishing, and evenings at world-class restaurants. Our boutique retreat blends active adventure with deep relaxation.',
    shortDescription: 'Luxury wellness & surf in lively Tamarindo.',
    location: 'Tamarindo, Guanacaste',
    region: 'Guanacaste',
    lat: 10.2992,
    lng: -85.8357,
    price: 185,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop',
    ],
    amenities: ['Surf Lessons', 'Yoga', 'Sport Fishing', 'Pool', 'WiFi', 'Restaurant'],
    rating: 4.7,
    reviewCount: 201,
    category: 'beach',
    duration: '7 days',
    maxGuests: 20,
    available: true,
    highlights: ['Sport fishing charter', 'ATV tour', 'Turtle nesting season tours', 'Salsa dancing class'],
    contactEmail: 'sunset@tamarindobeach.com',
  },
  {
    id: 'r9',
    name: 'Turrialba Whitewater & Yoga',
    description:
      'Adventure meets tranquility at our unique retreat near Turrialba, Costa Rica\'s whitewater capital. Challenge yourself on the legendary Pacuare River, one of the world\'s top whitewater rafting destinations, then recover with evening yoga and body work. A perfect blend of adrenaline and healing.',
    shortDescription: 'World-class rafting on the Pacuare River & restorative yoga.',
    location: 'Turrialba, Cartago',
    region: 'Caribbean Slope',
    lat: 9.9017,
    lng: -83.6800,
    price: 170,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&auto=format&fit=crop',
    ],
    amenities: ['Rafting', 'Yoga Studio', 'Sauna', 'Organic Meals', 'Equipment Rental'],
    rating: 4.8,
    reviewCount: 74,
    category: 'adventure',
    duration: '5 days',
    maxGuests: 20,
    available: true,
    highlights: ['Pacuare River Class IV rafting', 'Restorative yoga & bodywork', 'Jungle waterfall hike', 'Indigenous community visit'],
    contactEmail: 'river@turrialbayoga.com',
  },
  {
    id: 'r10',
    name: 'Nicoya Peninsula Detox Retreat',
    description:
      'The Nicoya Peninsula is one of the world\'s five Blue Zones — places where people regularly live past 100. Our detox and longevity retreat draws on the secrets of the Nicoya centenarians: plant-based nutrition, movement, purpose, and community. Transform your health and wellbeing in this extraordinary setting.',
    shortDescription: 'Longevity & detox in Costa Rica\'s Blue Zone.',
    location: 'Sámara, Guanacaste',
    region: 'Guanacaste',
    lat: 9.8837,
    lng: -85.5282,
    price: 240,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&auto=format&fit=crop',
    ],
    amenities: ['Juice Bar', 'Detox Program', 'Yoga', 'Meditation', 'Nutritionist', 'Beach Access'],
    rating: 4.9,
    reviewCount: 112,
    category: 'wellness',
    duration: '10 days',
    maxGuests: 12,
    available: true,
    highlights: ['Personalized detox plan', 'Blue Zone cooking classes', 'Centenarian community visit', 'Biohacking workshops'],
    contactEmail: 'detox@nicoyablue.com',
  },
  {
    id: 'r11',
    name: 'Cahuita Caribbean Healing',
    description:
      'Experience the vibrant Afro-Caribbean culture of Costa Rica\'s Caribbean coast at our healing retreat in Cahuita. Reggae rhythms, cacao ceremonies, traditional plant medicine, snorkeling in the coral reef, and authentic Caribbean cuisine create a deeply enriching and joyful experience.',
    shortDescription: 'Cacao ceremonies & coral reef snorkeling on the Caribbean.',
    location: 'Cahuita, Limón',
    region: 'Caribbean Coast',
    lat: 9.7350,
    lng: -82.8479,
    price: 155,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1604537466158-719b1972feb8?w=800&auto=format&fit=crop',
    ],
    amenities: ['Cacao Ceremonies', 'Snorkeling', 'Yoga', 'Caribbean Cuisine', 'Reef Tours'],
    rating: 4.7,
    reviewCount: 57,
    category: 'wellness',
    duration: '7 days',
    maxGuests: 16,
    available: true,
    highlights: ['Cacao ceremony', 'Coral reef snorkeling', 'Salsa & merengue classes', 'Traditional plant medicine'],
    contactEmail: 'healing@cahuitacaribbean.com',
  },
  {
    id: 'r12',
    name: 'Dominical Surf & Meditation',
    description:
      'Dominical is a small, authentic surf village that has retained its soul while welcoming travelers from around the world. Our retreat combines the discipline of daily surfing with the inner journey of meditation practice. Morning swims, afternoon sessions, and evening integration circles create a transformative week.',
    shortDescription: 'Authentic surf culture meets deep meditation in Dominical.',
    location: 'Dominical, Puntarenas',
    region: 'South Pacific',
    lat: 9.2570,
    lng: -83.8600,
    price: 165,
    priceUnit: 'per night',
    images: [
      'https://images.unsplash.com/photo-1455729552865-3658a5d39692?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=800&auto=format&fit=crop',
    ],
    amenities: ['Surf Lessons', 'Meditation Hall', 'Yoga', 'Organic Café', 'Waterfall Hikes'],
    rating: 4.8,
    reviewCount: 91,
    category: 'surf',
    duration: '7 days',
    maxGuests: 18,
    available: false,
    highlights: ['Daily surf instruction', 'Silent meditation mornings', 'Nauyaca waterfall hike', 'Breathwork & integration'],
    contactEmail: 'surf@dominicalmeditation.com',
  },
];
